title: Philomena Polefrone
description: Philomena Polefrone's Personal Website

url: https://themeinmena.github.io
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  email: prmpolefrone@gmail.com
  linkedin: 


